# Generated by Django 2.2.1 on 2020-10-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_app', '0002_auto_20200930_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_price', models.IntegerField()),
                ('menu_hot_ice', models.BooleanField()),
            ],
        ),
    ]
