# Generated by Django 2.2.1 on 2020-10-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_app', '0003_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateField()),
                ('order_menu', models.CharField(max_length=100)),
                ('order_num', models.IntegerField()),
                ('order_ing', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
