# Generated by Django 2.2.1 on 2020-10-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_app', '0005_auto_20201004_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_ing',
            field=models.BooleanField(default=True),
        ),
    ]
