# Generated by Django 2.2.1 on 2020-10-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_app', '0007_auto_20201004_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(default=0),
        ),
    ]
